src/Entity/Investisseur.php
<?php

namespace App\Entity;

use App\Repository\InvestisseurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvestisseurRepository::class)
 */
class Investisseur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_entreprise;

    /**
     * @ORM\OneToMany(targetEntity=Discussion::class, mappedBy="investisseur")
     */
    private $discussions;

    /**
     * @ORM\OneToMany(targetEntity=InvestirOffre::class, mappedBy="investisseur")
     */
    private $investirOffres;

    public function __construct()
    {
        $this->discussions = new ArrayCollection();
        $this->investirOffres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    /**
     * @return Collection<int, Discussion>
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function addDiscussion(Discussion $discussion): self
    {
        if (!$this->discussions->contains($discussion)) {
            $this->discussions[] = $discussion;
            $discussion->setInvestisseur($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussion $discussion): self
    {
        if ($this->discussions->removeElement($discussion)) {
            // set the owning side to null (unless already changed)
            if ($discussion->getInvestisseur() === $this) {
                $discussion->setInvestisseur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, InvestirOffre>
     */
    public function getInvestirOffres(): Collection
    {
        return $this->investirOffres;
    }

    public function addInvestirOffre(InvestirOffre $investirOffre): self
    {
        if (!$this->investirOffres->contains($investirOffre)) {
            $this->investirOffres[] = $investirOffre;
            $investirOffre->setInvestisseur($this);
        }

        return $this;
    }

    public function removeInvestirOffre(InvestirOffre $investirOffre): self
    {
        if ($this->investirOffres->removeElement($investirOffre)) {
            // set the owning side to null (unless already changed)
            if ($investirOffre->getInvestisseur() === $this) {
                $investirOffre->setInvestisseur(null);
            }
        }

        return $this;
    }
}

templates/pages/admin/activerCompte.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activer compte!{% endblock %}

{% block body %}
<style>

   .card{
     box-shadow: 0 0 12px 1px rgba(0, 0, 0, 0.4);
   }
</style>

                        <div class="row mt-5">

                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-body">
                                     <p style="color:blue; font-size:16px; font-weight:bold;">Activation comptes des utilisateurs : <span style="background-color:red; font-size:15px;color:white;border-radius:12px;padding:0px 5px;"> {{nb}}</span></p>
                                       <br>
                                        <div class="table-responsive">
                                            <table class="table table-centered table-nowrap mb-0">
                                                <thead class="thead-light">
                                                    <tr>
                                                       
                                                        <th>Nom Complet</th>
                                                        <th>Email</th>
                                                        <th>Rôle</th>
                                                        <th>Date inscription</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                 {% for user in user %}
                                                    <tr>
                                                        <td>{{user.username}}</td>
                                                        <td>{{user.email}}</td>
                                                        <td>{{user.role}}</td>
                                                        <td>{{user.dateInscription}}</td>
                                                       
                                                        <td> <a  href="{{ path('activationU', {'id': user.id}) }}" class="btn btn-outline-success btn-sm edit" title="Activer">
                                                                    <i class="dripicons-lock-open"></i>
                                                                </a>
                                                        </td>
                                                        <td> <a href="{{ path('find', {'id': user.id})}}" class="btn btn-outline-primary btn-sm edit" title="Show">
                                                                    <i style=" font-weight:bold;" class="dripicons-preview"></i>
                                                                </a>
                                                        </td>
                                                       
                                                    </tr>
                                                  
                                                     {% endfor %}
               

                                                </tbody>
                                            </table>
                                           
                                        </div>
                                            
                                        <!-- end table-responsive -->
                                    </div>
                                </div>
                            </div>
                         </div>


                        
 {% endblock %}

templates/pages/admin/popupInvestisseur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Investisseurs{% endblock %}

{% block body %}
<style>
.overlay {
  position: fixed;
  top: 100px;
  bottom: 0;
  left: 250px;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 40%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup h2 {
  margin-top: 0;
  color: #333;
  font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: blue;
}
.popup .close:hover {
  color: #06D85F;
}
.popup .content {
  max-height: 30%;
  overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
th{
    background: #3498db; 
	
}

</style>

                        <div class="row mt-5">

                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 style="color:blue;" class="header-title mb-4">Les Investisseurs : {{nb}}</h4>
                                        <div class="table-responsive">
                                            <table class="table table-centered table-nowrap mb-0">
                                                <thead class="thead-light">
                                                    <tr>
                                                       
                                                        <th>Nom Complet</th>
                                                        <th>Email</th>
                                                        <th>Pays</th>
                                                        <th>Nom Entreprise</th>
                                                        <th>Num Téléphone</th>
                                                        <th>Adresse</th>
                                                        <th>Date inscription</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                 {% for user in user %}
                                                    <tr>
                                                        <td>{{user.utilisateur.username}}</td>
                                                        <td>{{user.utilisateur.email}}</td>
                                                        <td>{{user.pays}}</td>
                                                        <td>{{user.nomEntreprise}}</td>
                                                        <td>{{user.utilisateur.tel}}</td>
                                                        <td>{{user.utilisateur.adresse}}</td>
                                                        <td>{{user.utilisateur.dateInscription}}</td>
                                                       
                                                        <td> <a  href="{{ path('desactivation', {'id': user.utilisateur.id}) }}" class="btn btn-outline-danger btn-sm edit" title="Desactiver">
                                                                    <i class="dripicons-lock"></i>
                                                                </a>
                                                        </td>
                                                        <td> <a href="{{ path('find', {'id': user.utilisateur.id})}}" class="btn btn-outline-primary btn-sm edit" title="Show">
                                                                    <i style=" font-weight:bold;" class="dripicons-preview"></i>
                                                                </a>
                                                        </td>
                                                       
                                                    </tr>
                                                  
                                                     {% endfor %}
               

                                                </tbody>
                                            </table>
                                           
                                        </div>
                                         <div class="overlay">
	                                                <div class="popup">
                                                       
                                                            {% for user2 in user2 %}
		                                                     <center>  <img class="rounded-circle" width="70px" src="/admin/assetsAdmin/images/admin.png">
                                                           <br><br><br>
                                                           <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Nom Complet : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.username}} <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Email : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.email}} <h5>
                                                                 </div>
                                                            </div>
                                                            
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Num Téléphone : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.tel}} <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Adresse : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.adresse}}</ <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Nom Entreprise : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.nomEntreprise}}</ <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Pays : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.pays}}</ <h5>
                                                                 </div>
                                                            </div>
                                                             
		                                                      <a class="close" href="{{ path('showInv')}}">&times;</a>
		                                                     
                                                              {% endfor %}
                                                        
                                                       
	                                                      </div>
                                                    </div> 
                                            
                                        <!-- end table-responsive -->
                                    </div>
                                </div>
                            </div>
                         </div>


                        
 {% endblock %}

templates/pages/admin/popupMinistere.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Ministéres{% endblock %}

{% block body %}
<style>
.overlay {
  position: fixed;
  top: 100px;
  bottom: 0;
  left: 250px;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 40%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup h2 {
  margin-top: 0;
  color: #333;
  font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: blue;
}
.popup .close:hover {
  color: #06D85F;
}
.popup .content {
  max-height: 30%;
  overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
th{
    background: #3498db; 
	
}

</style>

                        <div class="row mt-5">

                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 style="color:blue;" class="header-title mb-4">Les Ministéres : {{nb}}</h4>
                                        <div class="table-responsive">
                                            <table class="table table-centered table-nowrap mb-0">
                                                <thead class="thead-light">
                                                    <tr>
                                                       
                                                        <th>Nom Complet</th>
                                                        <th>Email</th>
                                                        <th>Type</th>
                                                        <th>Num Téléphone</th>
                                                        <th>Adresse</th>
                                                        <th>Date inscription</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                 {% for user in user %}
                                                    <tr>
                                                        <td>{{user.utilisateur.username}}</td>
                                                        <td>{{user.utilisateur.email}}</td>
                                                        <td>{{user.type.titre}}</td>
                                                        <td>{{user.utilisateur.tel}}</td>
                                                        <td>{{user.utilisateur.adresse}}</td>
                                                        <td>{{user.utilisateur.dateInscription}}</td>
                                                       
                                                        <td> <a  href="{{ path('desactivation', {'id': user.utilisateur.id}) }}" class="btn btn-outline-danger btn-sm edit" title="Desactiver">
                                                                    <i class="dripicons-lock"></i>
                                                                </a>
                                                        </td>
                                                        <td> <a href="{{ path('findM', {'id': user.utilisateur.id})}}" class="btn btn-outline-primary btn-sm edit" title="Show">
                                                                    <i style=" font-weight:bold;" class="dripicons-preview"></i>
                                                                </a>
                                                        </td>
                                                       
                                                    </tr>
                                                  
                                                     {% endfor %}
               

                                                </tbody>
                                            </table>
                                           
                                        </div>
                                        <div class="overlay">
	                                                <div class="popup">
                                                       
                                                           {% for user2 in user2 %}
                                                           <center>  <img class="rounded-circle" width="70px" src="/admin/assetsAdmin/images/admin.png">
                                                           <br><br><br>
                                                              <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Nom Complet : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.username}} <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Email : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.email}} <h5>
                                                                 </div>
                                                            </div>
                                                           
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Num Téléphone : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.tel}} <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Adresse : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.utilisateur.adresse}}</ <h5>
                                                                 </div>
                                                            </div>
                                                            <div class="row">
                                                                 <div class="col-lg-6">
                                                                  <h5>Type : </h5>
                                                                 </div>
                                                                  <div class="col-lg-6">
                                                                    <h5>{{user2.type.titre}}</ <h5>
                                                                 </div>
                                                            </div>
                                                            
		                                                       <a class="close" href="{{ path('showM')}}">&times;</a>
		                                                      
                                                              {% endfor %}
                                                        
                                                       
	                                                      </div>
                                                    </div> 
                                            
                                        <!-- end table-responsive -->
                                    </div>
                                </div>
                            </div>
                         </div>


                        
 {% endblock %}

templates/pages/admin/showInvestisseur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Investisseurs{% endblock %}

{% block body %}
<style>
.overlay {
  position: fixed;
  top: 100px;
  bottom: 0;
  left: 250px;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay:target {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 30%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup h2 {
  margin-top: 0;
  color: #333;
  font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: blue;
}
.popup .close:hover {
  color: #06D85F;
}
.popup .content {
  max-height: 30%;
  overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
th{
    background: #3498db; 
	
}
.card{
     box-shadow: 0 0 12px 1px rgba(0, 0, 0, 0.4);
   }

</style>

                        <div class="row mt-5">

                            <div class="col-xl-12">
                                <div class="card">
                                    <div class="card-body">
                                     
                                           <p style="color:blue; font-size:16px; font-weight:bold;">Les Investisseurs : <span style="background-color:red; font-size:15px;color:white;border-radius:12px;padding:0px 5px;"> {{nb}}</span></p>
                                       <br> <div class="table-responsive">
                                            <table class="table table-centered table-nowrap mb-0">
                                                <thead class="thead-light">
                                                    <tr>
                                                       
                                                        <th>Nom Complet</th>
                                                        <th>Email</th>
                                                       
                                                        <th>Date inscription</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                 {% for user in user %}
                                                    <tr>
                                                        <td>{{user.utilisateur.username}}</td>
                                                        <td>{{user.utilisateur.email}}</td>
                                                      
                                                        <td>{{user.utilisateur.dateInscription}}</td>
                                                       
                                                        <td> <a  href="{{ path('desactivationU', {'id': user.utilisateur.id}) }}" class="btn btn-outline-danger btn-sm edit" title="Desactiver">
                                                                    <i class="dripicons-lock"></i>
                                                                </a>
                                                        </td>
                                                        <td> <a href="{{ path('findInv', {'id': user.utilisateur.id})}}" class="btn btn-outline-primary btn-sm edit" title="Show">
                                                                    <i style=" font-weight:bold;" class="dripicons-preview"></i>
                                                                </a>
                                                        </td>
                                                       
                                                    </tr>
                                                  
                                                     {% endfor %}
               

                                                </tbody>
                                            </table>
                                           
                                        </div>
                                            
                                        <!-- end table-responsive -->
                                    </div>
                                </div>
                            </div>
                         </div>


                        
 {% endblock %}